version: '2'

services:
  WIKIJS:
  image: requarks/wiki:latest
  environment:
  volumes:
    - /wiki/data/content  
  ports:
    - 3000:3000
    - 3443:3443  

  POSTGRES:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "A DEFINIR"
      TZ: GMT-3
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5432:5432
    volumes:
      - "/opt/postgres/data:/var/lib/postgresql/data/pgdata:Z"
      - "/opt/postgres/transfer:/opt/transfer" 
      
  PGADMIN:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "SEUEMAIL@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "SUASENHA"
    ports:
      - 5050:80